import { getLedgerSnapshot } from "./ledger";
import { buildPublisherKit } from "./publisher-kit";
import { buildSubmissionReport } from "./submission";
import { buildAnswerProof } from "./answer-proof";
import { buildImpactGraph } from "./impact-graph";
import { spendPermitSummary } from "./spend-permits";
import { buildTractionCampaign } from "./traction";
import { buildTransparencyLog } from "./transparency-log";
import { volumeEngineSummary } from "./volume-engine";

export function buildProofPack(origin?: string) {
  const ledger = getLedgerSnapshot();
  const report = buildSubmissionReport();
  const publisherKit = buildPublisherKit(origin);
  const answerProof = buildAnswerProof(undefined, origin);
  const impactGraph = buildImpactGraph();
  const spendPermits = spendPermitSummary();
  const tractionCampaign = buildTractionCampaign(origin);
  const transparencyLog = buildTransparencyLog();
  const volumeEngine = volumeEngineSummary();

  return {
    generatedAt: new Date().toISOString(),
    project: report.project,
    verdict:
      "Kleos differentiates from generic x402 demos by proving the full creator value loop: inspect, cite, split, reprice, and retroactively reward what mattered.",
    strongestDifferentiators: [
      "Two-stage economics: read tolls unlock sources, citation tolls pay only sources used in final answers.",
      "Answer-linked receipts: every citation has an answer hash, support span, read payment, citation payment, confidence, and receipt hash.",
      "Claim-level proof: finalized answers expose covered, partial, and unsupported claims with receipt-backed support traces.",
      "Impact graph: source, read-payment, citation, claim, split, creator, impact, and cash-out nodes expose how information turns into creator settlement.",
      "Creator operations: signed webhook delivery records and Arc-ready cash-out records are generated from citation and impact settlement.",
      "Creator earnings page: /creators gives each creator a public ledger of read toll splits, citation toll splits, impact rewards, sources, wallets, and cash-out records.",
      "Adversarial audit layer: receipts can be independently verified and weak citations can put the broker bond at risk.",
      "Transparency log: payments, citation receipts, splits, impact grants, cash-outs, verifications, and challenges roll into a public root hash with per-entry inclusion proofs.",
      "Tester attestation loop: every tester can mint a signed proof hash and prefilled GitHub issue from the live app.",
      "GitHub tester issue template: public feedback is structured so /api/traction/github can count real scenario runs, roles, and proof hashes.",
      "Traction campaign kit: role-specific tester links, curl payloads, Discord copy, X copy, and success gates make external validation repeatable.",
      "Tester invite packet: /api/traction/invite emits role-specific /test links, DMs, social copy, API curls, and the exact roles still needed to close public traction gates.",
      "Hosted one-click tester flow: /api/tester/one-click runs the no-wallet scenario, verifies a receipt, mints a proof hash, and returns the public GitHub issue URL.",
      "Public tester page: /test gives nontechnical testers a form-driven path to create a proof hash and submit durable GitHub feedback.",
      "Public traction command center: /traction shows live GitHub gates, role-specific invite links, outreach copy, and judge proof links in one reviewer-readable surface.",
      "Autonomous volume engine: /api/volume/engine lets reviewers run labeled internal agent batches that inspect paid sources, settle citation tolls, and allocate impact rewards without counting them as external traction.",
      "One-command tester runner: scripts/tester-run.ps1 executes the live no-wallet scenario, verifies proof surfaces, mints a proof hash, and prints the public GitHub issue URL.",
      "Public operations proof: status, health, treasury, and OpenAPI endpoints let async judges verify scope and liveness without a guided demo.",
      "Proof explorer: /proof turns the live x402 receipt, score certificate, transparency root, impact graph, and traction gates into a reviewer-readable audit console.",
      "Submission certificate: /api/provenance and /api/submission/certificate tie deployment, GitHub repo, CI, Circle x402 receipt, rubric score, and traction gates into one machine-readable proof.",
      "Submission evidence bundle: /api/submission/bundle packages form fields, demo script, proof links, tester invite links, score gates, and a bundle hash for async judges.",
      "Sponsored no-wallet trial: one endpoint runs inspect, read toll, citation toll, impact, and reprice flow under explicit spend caps.",
      "Source registry: creator-scoped source IDs, IPFS-shaped metadata/content CIDs, split digests, and a deployable Arc SourceRegistry contract.",
      "Live RSS/Atom import: creators can paste a feed URL and Kleos registers recent entries as x402-priced sources with feed-derived previews and citation tolls.",
      "Publisher ownership verification: source owners can publish a Kleos challenge in /.well-known/kleos.json or a feed proof before new sources are marked owner-verified.",
      "Reputation passport: /api/reputation/passport exports ERC-8004-ready local reputation for buyer agents, creators, publishers, and Kleos without claiming onchain registration.",
      "Encrypted content vault: public ciphertext plus x402-gated AES-GCM key release proves paid access can protect creator content beyond previews.",
      "A2A paid research: external agents can pay /api/a2a/ask over x402; Kleos then pays creators and returns answer-linked settlement proof.",
      "Agent card discovery: /.well-known/agent-card.json exposes Kleos' wallet, x402 schemes, service endpoints, proof links, and ERC-8004-ready identity posture.",
      "Agent spend permits: /api/agents/spend-permits issues budget-capped, tool-scoped, expiry-bound permits so external agents cannot silently overspend while buying and citing sources.",
      "JSON-RPC MCP server: /.well-known/mcp.json and /api/mcp/rpc expose callable tools and resources for agent integration.",
      "Packaged MCP bridge: packages/kleos-mcp gives builders a dependency-light stdio connector that can be published as npx -y kleos-mcp.",
      "Economic invariant CI: budget caps, split totals, receipt links, registry records, vault gates, A2A gates, and score honesty are checked by scripts/invariant-check.ps1 and GitHub Actions.",
      "OSS kit: builders get copy-paste agent, publisher, proof, webhook, cash-out, and attestation integration steps.",
      "Retroactive impact pool: sponsor capital is allocated after citations prove which sources changed the answer.",
      "Publisher kit: a concrete /.well-known/kleos.json path for RSS/Ghost creators and crawler payment policy.",
      "Citation-aware seller pricing: prices react to paid reads, skipped demand, citation rate, confidence, and uncited purchases.",
    ],
    judgeSequence: [
      "Run scenario",
      "Open /api/dashboard/ledger",
      "Open /api/status",
      "Open /api/treasury",
      "Open /api/openapi",
      "Open /.well-known/agent-card.json",
      "Open /proof for the public proof explorer",
      "Open /api/provenance",
      "Open /api/submission/certificate",
      "Open /api/submission/bundle",
      "Open /api/registry/sources",
      "POST /api/sources/import-rss",
      "POST /api/publishers/verify",
      "Open /api/reputation/passport",
      "POST /api/agents/spend-permits to issue a bounded external-agent spend permit",
      "Open /api/vault/ci_arc_gateway_notes",
      "POST /api/a2a/ask",
      "POST /api/mcp/rpc tools/list and tools/call",
      "Run node packages/kleos-mcp/bin/kleos-mcp.js --list-tools",
      "Open /api/proof-pack",
      "Open /api/answers/proof",
      "Open /api/impact/graph",
      "Open /api/transparency/log and /api/transparency/proof/:id",
      "Open /creators for the creator earnings ledger",
      "POST /api/trial/sponsored",
      "POST /api/webhooks/dispatch",
      "POST /api/creators/cashout",
      "POST /api/receipts/verify",
      "POST /api/citations/challenge",
      "POST /api/traction/attest",
      "POST /api/tester/one-click",
      "Open /test for the public tester page",
      "Open /traction for the public traction command center",
      "Open /api/traction/invite?role=creator and /api/traction/invite?role=builder",
      "Run scripts/tester-run.ps1 to mint a proof hash and public GitHub issue URL",
      "Open /api/traction/campaign",
      "Open /api/traction/github",
      "POST /api/volume/engine to generate a labeled internal autonomous volume batch",
      "Open /api/oss-kit",
      "Open /api/competitive/positioning",
      "Open /api/publisher-kit",
      "Run corepack pnpm smoke",
      "Run corepack pnpm invariants",
      "Review the live Circle CLI Gateway receipt and Arcscan link on the stable public URL",
    ],
    rubric: report.rubric,
    metrics: ledger.metrics,
    gatewayProof: ledger.gatewayProof,
    latestAnswerSettlement: ledger.answerSettlements[0] ?? null,
    latestAnswerProof: answerProof,
    spendPermits,
    impactGraph: {
      graphHash: impactGraph.graphHash,
      summary: impactGraph.summary,
      sampleNodes: impactGraph.nodes.slice(0, 8),
      sampleEdges: impactGraph.edges.slice(0, 8),
    },
    latestCitationReceipts: ledger.citationReceipts.slice(0, 5),
    impactGrants: ledger.impactGrants.slice(0, 8),
    creatorWebhooks: ledger.creatorWebhooks.slice(0, 8),
    webhookDeliveries: ledger.webhookDeliveries.slice(0, 8),
    creatorCashouts: ledger.creatorCashouts.slice(0, 8),
    receiptVerifications: ledger.receiptVerifications.slice(0, 8),
    citationChallenges: ledger.citationChallenges.slice(0, 8),
    testerAttestations: ledger.testerAttestations.slice(0, 8),
    tractionCampaign,
    volumeEngine,
    transparencyLog: {
      schema: transparencyLog.schema,
      rootHash: transparencyLog.rootHash,
      entryCount: transparencyLog.entryCount,
      totals: transparencyLog.totals,
      sampleEntries: transparencyLog.entries.slice(0, 5),
    },
    durableTractionVerifier: origin ? `${origin}/api/traction/github` : "/api/traction/github",
    publisherKit: publisherKit.wellKnownManifest,
    apiSurfaces: [
      "GET /api/catalog",
      "GET /api/status",
      "GET /api/health",
      "GET /api/treasury",
      "GET /api/openapi",
      "GET /api/content/:id",
      "GET /api/registry/sources",
      "GET /api/vault/:id",
      "POST /api/vault/:id/key",
      "POST /api/a2a/ask",
      "POST /api/agent/ask",
      "GET /api/agents/spend-permits",
      "POST /api/agents/spend-permits",
      "GET /.well-known/mcp.json",
      "GET /.well-known/agent-card.json",
      "GET /api/agent-card",
      "POST /api/mcp/rpc",
      "POST /api/trial/sponsored",
      "POST /api/agent/research",
      "POST /api/citations/finalize",
      "GET /api/answers/proof",
      "POST /api/impact/settle",
      "GET /api/impact/graph",
      "POST /api/webhooks/dispatch",
      "POST /api/creators/cashout",
      "GET /api/receipts/verify",
      "POST /api/receipts/verify",
      "GET /api/transparency/log",
      "GET /api/transparency/proof/:id",
      "GET /api/citations/challenge",
      "POST /api/citations/challenge",
      "GET /api/traction/attest",
      "POST /api/traction/attest",
      "GET /api/traction/campaign",
      "GET /api/traction/github",
      "GET /api/volume/engine",
      "POST /api/volume/engine",
      "GET /api/tester/one-click",
      "POST /api/tester/one-click",
      "GET /test",
      "GET /traction",
      "GET /proof",
      "GET /creators",
      "POST /api/pricing/recompute",
      "POST /api/sources/register",
      "POST /api/sources/import-rss",
      "GET /api/publishers/verify",
      "POST /api/publishers/verify",
      "GET /api/reputation/passport",
      "POST /api/reputation/passport",
      "GET /api/mcp",
      "GET /api/publisher-kit",
      "GET /api/oss-kit",
      "GET /api/competitive/positioning",
      "GET /api/proof-pack",
      "GET /api/provenance",
      "GET /api/submission/certificate",
      "GET /api/submission/bundle",
      "GET /api/submission/report",
    ],
    openDeploymentItems: [
      "3-5 external tester runs or creator source registrations",
      "Final demo video under 3 minutes",
    ],
  };
}
