import { getLedgerSnapshot } from "./ledger";
import { buildPublisherKit } from "./publisher-kit";
import { buildSubmissionReport } from "./submission";
import { buildAnswerProof } from "./answer-proof";
import { buildTractionCampaign } from "./traction";

export function buildProofPack(origin?: string) {
  const ledger = getLedgerSnapshot();
  const report = buildSubmissionReport();
  const publisherKit = buildPublisherKit(origin);
  const answerProof = buildAnswerProof(undefined, origin);
  const tractionCampaign = buildTractionCampaign(origin);

  return {
    generatedAt: new Date().toISOString(),
    project: report.project,
    verdict:
      "Kleos differentiates from generic x402 demos by proving the full creator value loop: inspect, cite, split, reprice, and retroactively reward what mattered.",
    strongestDifferentiators: [
      "Two-stage economics: read tolls unlock sources, citation tolls pay only sources used in final answers.",
      "Answer-linked receipts: every citation has an answer hash, support span, read payment, citation payment, confidence, and receipt hash.",
      "Claim-level proof: finalized answers expose covered, partial, and unsupported claims with receipt-backed support traces.",
      "Creator operations: signed webhook delivery records and Arc-ready cash-out records are generated from citation and impact settlement.",
      "Adversarial audit layer: receipts can be independently verified and weak citations can put the broker bond at risk.",
      "Tester attestation loop: every tester can mint a signed proof hash and prefilled GitHub issue from the live app.",
      "GitHub tester issue template: public feedback is structured so /api/traction/github can count real scenario runs, roles, and proof hashes.",
      "Traction campaign kit: role-specific tester links, curl payloads, Discord copy, X copy, and success gates make external validation repeatable.",
      "Public operations proof: status, health, treasury, and OpenAPI endpoints let async judges verify scope and liveness without a guided demo.",
      "Sponsored no-wallet trial: one endpoint runs inspect, read toll, citation toll, impact, and reprice flow under explicit spend caps.",
      "Source registry: creator-scoped source IDs, IPFS-shaped metadata/content CIDs, split digests, and a deployable Arc SourceRegistry contract.",
      "Encrypted content vault: public ciphertext plus x402-gated AES-GCM key release proves paid access can protect creator content beyond previews.",
      "A2A paid research: external agents can pay /api/a2a/ask over x402; Kleos then pays creators and returns answer-linked settlement proof.",
      "Economic invariant CI: budget caps, split totals, receipt links, registry records, vault gates, A2A gates, and score honesty are checked by scripts/invariant-check.ps1 and GitHub Actions.",
      "OSS kit: builders get copy-paste agent, publisher, proof, webhook, cash-out, and attestation integration steps.",
      "Retroactive impact pool: sponsor capital is allocated after citations prove which sources changed the answer.",
      "Publisher kit: a concrete /.well-known/kleos.json path for RSS/Ghost creators and crawler payment policy.",
      "Citation-aware seller pricing: prices react to paid reads, skipped demand, citation rate, confidence, and uncited purchases.",
    ],
    judgeSequence: [
      "Run scenario",
      "Open /api/dashboard/ledger",
      "Open /api/status",
      "Open /api/treasury",
      "Open /api/openapi",
      "Open /api/registry/sources",
      "Open /api/vault/ci_arc_gateway_notes",
      "POST /api/a2a/ask",
      "Open /api/proof-pack",
      "Open /api/answers/proof",
      "POST /api/trial/sponsored",
      "POST /api/webhooks/dispatch",
      "POST /api/creators/cashout",
      "POST /api/receipts/verify",
      "POST /api/citations/challenge",
      "POST /api/traction/attest",
      "Open /api/traction/campaign",
      "Open /api/traction/github",
      "Open /api/oss-kit",
      "Open /api/competitive/positioning",
      "Open /api/publisher-kit",
      "Run corepack pnpm smoke",
      "Run corepack pnpm invariants",
      "Review the live Circle CLI Gateway receipt and Arcscan link on the stable public URL",
    ],
    rubric: report.rubric,
    metrics: ledger.metrics,
    gatewayProof: ledger.gatewayProof,
    latestAnswerSettlement: ledger.answerSettlements[0] ?? null,
    latestAnswerProof: answerProof,
    latestCitationReceipts: ledger.citationReceipts.slice(0, 5),
    impactGrants: ledger.impactGrants.slice(0, 8),
    creatorWebhooks: ledger.creatorWebhooks.slice(0, 8),
    webhookDeliveries: ledger.webhookDeliveries.slice(0, 8),
    creatorCashouts: ledger.creatorCashouts.slice(0, 8),
    receiptVerifications: ledger.receiptVerifications.slice(0, 8),
    citationChallenges: ledger.citationChallenges.slice(0, 8),
    testerAttestations: ledger.testerAttestations.slice(0, 8),
    tractionCampaign,
    durableTractionVerifier: origin ? `${origin}/api/traction/github` : "/api/traction/github",
    publisherKit: publisherKit.wellKnownManifest,
    apiSurfaces: [
      "GET /api/catalog",
      "GET /api/status",
      "GET /api/health",
      "GET /api/treasury",
      "GET /api/openapi",
      "GET /api/content/:id",
      "GET /api/registry/sources",
      "GET /api/vault/:id",
      "POST /api/vault/:id/key",
      "POST /api/a2a/ask",
      "POST /api/agent/ask",
      "POST /api/trial/sponsored",
      "POST /api/agent/research",
      "POST /api/citations/finalize",
      "GET /api/answers/proof",
      "POST /api/impact/settle",
      "POST /api/webhooks/dispatch",
      "POST /api/creators/cashout",
      "GET /api/receipts/verify",
      "POST /api/receipts/verify",
      "GET /api/citations/challenge",
      "POST /api/citations/challenge",
      "GET /api/traction/attest",
      "POST /api/traction/attest",
      "GET /api/traction/campaign",
      "GET /api/traction/github",
      "POST /api/pricing/recompute",
      "POST /api/sources/register",
      "GET /api/mcp",
      "GET /api/publisher-kit",
      "GET /api/oss-kit",
      "GET /api/competitive/positioning",
      "GET /api/proof-pack",
      "GET /api/submission/report",
    ],
    openDeploymentItems: [
      "3-5 external tester runs or creator source registrations",
      "Final demo video under 3 minutes",
    ],
  };
}
